### ISSUE TITLE
Custom CSS Won't Load from /Assets

### ISSUE THREAD

**Issue by PhoenixSheppy** [upptime/upptime#468] opened 2021-11-05 15:57 UTC
Hi there! I've been using UptimeKuma for a while, and figured I'd give this a try since it would greatly decrease the upkeep required, an eliminate a VPS that I need to monitor / maintain.

As described in your documentation, I placed a custom .css file into the /assets folder, and then used logoUrl: to specify said location.
![image](https://user-images.githubusercontent.com/20131900/140539970-39fb0f46-4231-4a9c-b28f-7154db63d815.png)

In result, I get 404's from the webpage specifying that the file doesn't exist.
![image](https://user-images.githubusercontent.com/20131900/140539934-4bc67c3f-804c-4e92-8df8-ae262098201e.png)|

I checked the build workflow, and everything seems OK, but I'm stumped to why this isn't working! I was able to get generic themes working (night, dark, light, etc.) but not custom ones?

The repo with my fork is located here: https://github.com/Phoenix-Net/PhoenixNet-Status-Page

Thoughts?

**Comment by GrahamSH-LLK** [comment] 2021-11-16 00:40
It looks like it's working to me. Maybe it was somehow cached?

**Comment by PhoenixSheppy** [comment] 2021-11-16 01:01
@GrahamSH-LLK I loaded it using an alternative method, and storing it in another Github repo. Not the intended way.

**Comment by jayantkatia** [comment] 2021-12-13 17:56
Hey @PhoenixSheppy, 
I had a similar issue. I changed the url to  ``` https://raw.githubusercontent.com/USERNAME/REPO_NAME/BRANCH_NAME/PATH ``` and it worked.

I skimmed through your ```.upptimerc.yml``` history and found that you [used raw URL once](https://github.com/Phoenix-Net/PhoenixNet-Status-Page/commit/84df8997a8077af1482d54137fe6dffa932266dd#diff-7e74aaada79c412c8e858e9c440ce132f8ad55d76fc8056006181b6c3492fe1dR46). But, your directory structure in the image does not match with your URL.
 
It should be ``` https://raw.githubusercontent.com/Phoenix-Net/PhoenixNet-Status-Page/master/assets/DarkBlue.css``` instead of ```https://raw.githubusercontent.com/Phoenix-Net/PhoenixNet-Status-Page/master/assets/themes/DarkBlue.css ```

**Comment by KaspianDev** [comment] 2022-05-26 16:12
> I kind of encounter a similar issue. But for me is the issue that for whatever reasons the CSS file isn't transferred from the `assets` directory into the `gh-pages` branch as it should according to the docs.
> 
> And since I don't know which action is using the gh-pages one can I also not figure out what settings may prevent this...

Can confirm this.

**Comment by KaspianDev** [comment] 2022-05-26 17:13
Workaround: use statically
https://cdn.statically.io/gh/GITHUB-ACCOUNT/REPO/BRANCH/assets/CSSFILE.css

**Comment by ray960129** [comment] 2022-06-07 07:21
> 解決方法：靜態使用 https://cdn.statically.io/gh/GITHUB-ACCOUNT/REPO/BRANCH/assets/CSSFILE.css

Helpful, thanks.

**Comment by KevinRoebert** [comment] 2022-12-01 09:41
Any update on this issue? File are not transferred from the **assets** folder to the **gh-pages** branch.

**Comment by 6bccaf5c96a8d1c7** [comment] 2023-02-27 00:09
Posting to confirm this is still broken @AnandChowdhary

**Comment by eliasleyton** [comment] 2023-05-03 21:32
Css files are not being copied to the gh-pages branch in build process.

**Comment by tiarebalbi** [comment] 2023-12-02 19:59
+1 this issue still happening. none of the files are being copied over the gh-pages branch.

**Comment by netz0network** [comment] 2023-12-16 06:31
Confirmed. Still happening. Using the RAW url works but not ideally if you are using a custom domain for the page.

**Comment by netz0network** [comment] 2023-12-16 06:41
> Css files are not being copied to the gh-pages branch in build process.

Not only CSS files, no files are copied.

**Comment by AnandChowdhary** [comment] 2023-12-16 19:23
Fixed in https://github.com/upptime/uptime-monitor/releases/tag/v1.34.2!

Can you please test by manually running "Update Template CI" and after it's complete, running "Status Site CI"?

**Closed by AnandChowdhary** 2023-12-16 19:23 UTC
Labels: bug

**Comment by Andre601** [comment] 2023-12-16 19:39
> Fixed in https://github.com/upptime/uptime-monitor/releases/tag/v1.34.2!
> 
> Can you please test by manually running "Update Template CI" and after it's complete, running "Status Site CI"?

I think you mean Static Site CI?

**Comment by Andre601** [comment] 2023-12-16 19:47
Also, while making a PR did I notice that it triggers the "Setup CI" run. Tho, from what I saw did it not trigger for the two commits I made on that separate branch. Only when I created a PR for it to be merged into the main one did it trigger a run, causing extra commits and file changes on the PR...

Is this intentional?

**Comment by AnandChowdhary** [comment] 2023-12-16 19:55
The rule is to run Setup CI when `.upptimerc.yml` is changed.

**Comment by Andre601** [comment] 2023-12-16 20:34
> The rule is to run Setup CI when `.upptimerc.yml` is changed.

It should be updated then imo to only trigger on master/main pushes, to avoid extra CI runs that only get overriden during a merge.

**Comment by AnandChowdhary** [comment] 2023-12-17 11:43
You're right, happy to accept a PR that changes the default workflow and adds both "master" and "main" branches. And perhaps we have a configuration property to let people configure the name of the default branch?

**Comment by Andre601** [comment] 2023-12-17 19:40
> You're right, happy to accept a PR that changes the default workflow and adds both "master" and "main" branches. And perhaps we have a configuration property to let people configure the name of the default branch?

I can quickly make a PR (From what I saw is [this](https://github.com/upptime/uptime-monitor/blob/master/src/helpers/workflows.ts#L102-L169) the location to update?). Not sure how I would implement the branch option tho, so it would be something someone else has to do...
