### ISSUE TITLE
Overall uptime displays two percentage characters

### ISSUE THREAD

**Issue by idleberg** [upptime/upptime#93] opened 2020-11-27 09:51 UTC
On the summary page, the percent value is printed with two %-characters. Would have loved to submit a PR, but this is hard to track down

![Screenshot 2020-11-27 at 10 42 18](https://user-images.githubusercontent.com/1504938/100434750-4163f280-309d-11eb-9539-ee939758efb0.png)

**Comment by AnandChowdhary** [comment] 2020-11-27 10:31
Duplicate of https://github.com/upptime/upptime/issues/92

**Closed by AnandChowdhary** 2020-11-27 10:31 UTC
Labels: duplicate

**Comment by almaashy-99** [comment] 2020-12-31 21:11
Mohammed
