### ISSUE TITLE
Issue not closing itself

### ISSUE THREAD

**Issue by Proxymiity** [upptime/upptime#255] opened 2021-02-12 08:05 UTC
**Describe the bug**
Issue opened by upptime when a site went down does not close itself after the site is back online.

**To Reproduce**
1. Use a website with a http address
2. Make it down
3. See that an issue has been opened on the repository
4. Make it up
5. See that the issue has not been closed. (see [this](https://github.com/Proxymiity/status/issues/1) issue)

**Expected behavior**
The issue should close itself as the website is now up.

**Screenshots**
![image](https://i.iya.at/chrome_NN7HKC.png)
![image](https://i.iya.at/chrome_Gkk3I0.png)  
As you can see here, the host is up and there's still an active incident about it.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - 88.0.4324.150 (Official Build) (64-bit) (cohort: Stable)

**Smartphone (please complete the following information):**
 - Device: iPhone 11 Pro
 - OS: iOS 14.4
 - Safari

**Additional context**
~~Each website use an hidden address. This may be the matter.~~ tested on a repo with a public URL. did not change anything.

**Comment by AnandChowdhary** [comment] 2021-02-12 13:33
I see that this issue is already closed, did you manually close it?

**Comment by Proxymiity** [comment] 2021-02-12 14:01
I closed it myself. I have tested this on a brand new repo (which I deleted), it opened an issue and did not close it when the incident was resolved.

**Comment by AnandChowdhary** [comment] 2021-02-25 09:56
Can you share a link to the new repo? This was closed automatically yesterday: https://github.com/upptime/upptime/issues/269 so I am unable to reproduce it.

**Comment by AnandChowdhary** [comment] 2021-02-25 15:46
I tested it again and it looks good: https://github.com/koj-co/status.kojdev.com/issues/1#issuecomment-785935479.

**Closed by AnandChowdhary** 2021-02-25 15:46 UTC
Labels: bug

**Comment by Proxymiity** [comment] 2021-02-25 15:48
Sorry for the response delay. Missed the first notification. So, could you explain why [this issue](https://github.com/Proxymiity/status/issues/3) isn't closing itself?
