### ISSUE TITLE
Uptime CI action/task fails check status step 

### ISSUE THREAD

**Issue by iamlasse** [upptime/upptime#555] opened 2022-05-11 12:28 UTC
Uptime CI action task fails with error in check status step 

`Check status
could not read Username for 'https://github.com': terminal prompts disabled`

Expected result OK.

<img width="2560" alt="Screenshot 2022-05-11 at 14 25 33" src="https://user-images.githubusercontent.com/556886/167849702-8b8b83ab-81f6-4ee6-81d9-9e59bb87459e.png">
<img width="2560" alt="Screenshot 2022-05-11 at 14 28 05" src="https://user-images.githubusercontent.com/556886/167849772-29da36db-8da0-4dd8-b542-ef84652a80a2.png">

**Comment by mariojmdavid** [comment] 2022-05-18 06:56
I have this issue, is there a timeline to work on or some mitigation I can do?

**Comment by mariojmdavid** [comment] 2022-05-18 07:09
apologies, expired token
forget my comment

**Comment by mariojmdavid** [comment] 2022-05-18 08:02
there is an issue after all, 
continues with this error after I renew my personal token

**Comment by AnandChowdhary** [comment] 2022-05-18 09:42
Super weird that I can't reproduce this: https://github.com/pabio-status/production/runs/6486737330?check_suite_focus=true

I think it could be because we use HTTP and not SSH maybe? Or it could be related to [MFA](https://github.blog/2022-05-04-software-security-starts-with-the-developer-securing-developer-accounts-with-2fa/)?

Does anyone have a link to their public repo where I can see this error?

**Comment by AnandChowdhary** [comment] 2022-05-18 09:43
In fact from the screenshot it looks like actions/checkout is failing.

**Comment by Turtle84375** [comment] 2022-05-18 19:00
Just started happening with me too.

> Does anyone have a link to their public repo where I can see this error?

https://github.com/Turtle84375/status/actions/workflows/uptime.yml

Same error as OP:
https://github.com/Turtle84375/status/runs/6495336537?check_suite_focus=true

**Comment by xarcanix** [comment] 2022-05-19 09:41
same problem here, I was trying to use another version of checkout like @v3, but the problem is still there.

![uptime_issue](https://user-images.githubusercontent.com/88488406/169263822-c621dbe2-f0fe-45ca-a05d-c839a1012d47.png)

**Comment by Turtle84375** [comment] 2022-05-20 05:54
For me, it turned out to be that my personal access token had expired, regenerating it caused it to start working again with no issues.

> there is an issue after all, continues with this error after I renew my personal token

@mariojmdavid Has it started working again for you? I had to manually run the workflow(s) to get it going again.

**Comment by xarcanix** [comment] 2022-05-20 06:48
after renewing the token that works again, @Turtle84375 thanks!

**Comment by ooliver1** [comment] 2022-05-20 17:39
can also confirm it was the PAT, re run workflows manually (`Uptime CI`)

**Comment by AnandChowdhary** [comment] 2022-05-20 17:47
Awesome, then let's reopen this if someone else has the same issue that can't be fixed by updating their PAT :)

**Closed by AnandChowdhary** 2022-05-20 17:47 UTC
Labels: bug

**Comment by mariojmdavid** [comment] 2022-05-25 07:24
issue solved after new PAT and manual run of actions
