### ISSUE TITLE
Please use [actions/checkout] Release v4

### ISSUE THREAD

**Issue by thomasmerz** [upptime/upptime#871] opened 2023-10-25 12:16 UTC
There has been a major update for [actions/checkout](https://github.com/actions/checkout/releases/tag/v4.0.0).

So please use v4 instead of old v3.

**Comment by AnandChowdhary** [comment] 2023-12-16 19:34
@EmnichtdaYT I'm going to close this for now since this is not a bug.

**Closed by AnandChowdhary** 2023-12-16 19:34 UTC
Labels: bug

**Comment by thomasmerz** [comment] 2023-12-22 13:10
@AnandChowdhary , here's my PR with the update.

**Comment by AnandChowdhary** [comment] 2023-12-22 13:39
@thomasmerz This needs to be updated in the file where we programmatically create workflows in the repository upptime/uptime-monitor.

**Comment by thomasmerz** [comment] 2023-12-22 13:41
@AnandChowdhary - https://github.com/upptime/uptime-monitor/pull/238 should be the right repo / PR!?
