### ISSUE TITLE
Lack of error checking in site generation

### ISSUE THREAD

**Issue by nijel** [upptime/upptime#454] opened 2021-10-05 06:35 UTC
**Describe the bug**

https://github.com/upptime/upptime/issues/453 caused some dependency not being installed. Unfortunately, this doesn't make fail the whole action as none of the exec status code. In the end this removes all static content instead of failing the action.

**To Reproduce**
1. Make one of the steps fail (https://github.com/upptime/upptime/issues/453  is a good example)
2. Trigger "Static Site CI"
3. See the action does not fail
4. But at the same time all content from `gh-pages` branch is removed, so the status page no longer works

**Expected behavior**
The action should fail and not remove existing content.

**Screenshots**
See https://github.com/upptime/upptime/issues/453 or 
https://github.com/weblate-status-bot/status/runs/3798528109?check_suite_focus=true#step:3:41

**Additional context**
The code should check the return value from each of the shelljs invocations in https://github.com/upptime/uptime-monitor/blob/master/src/site.ts and fail the action in case it fails. See https://github.com/shelljs/shelljs#shellstringstr

**Comment by AnandChowdhary** [comment] 2021-10-05 06:42
Closing as duplicate of https://github.com/upptime/upptime/issues/453.

Thanks for opening!

**Closed by AnandChowdhary** 2021-10-05 06:42 UTC
Labels: bug
