### ISSUE TITLE
All workflows except for 'Update Template' fails to run

### ISSUE THREAD

**Issue by AnnikaV9** [upptime/upptime#981] opened 2024-07-04 23:48 UTC
**Describe the bug**
All workflows fail to run with the error:
```
Error: The module '/home/runner/work/_actions/upptime/uptime-monitor/v1.30.0/dist/lib/binding/node_libcurl.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 93. This version of Node.js requires
NODE_MODULE_VERSION 115. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1454:18)
    at Module.load (node:internal/modules/cjs/loader:1208:32)
    at Function.Module._load (node:internal/modules/cjs/loader:1024:12)
    at Module.require (node:internal/modules/cjs/loader:1233:19)
    at require (node:internal/modules/helpers:179:18)
    at Object.17001 (/home/runner/work/_actions/upptime/uptime-monitor/v1.30.0/webpack:/@upptime/uptime-monitor/node_modules/node-libcurl/lib/binding/node_libcurl.node:1:1)
    at __nccwpck_require__ (/home/runner/work/_actions/upptime/uptime-monitor/v1.30.0/webpack:/@upptime/uptime-monitor/webpack/bootstrap:21:1)
    at Object.30376 (/home/runner/work/_actions/upptime/uptime-monitor/v1.30.0/webpack:/@upptime/uptime-monitor/node_modules/node-libcurl/dist/Easy.js:5:1)
    at __nccwpck_require__ (/home/runner/work/_actions/upptime/uptime-monitor/v1.30.0/webpack:/@upptime/uptime-monitor/webpack/bootstrap:21:1)
    at Object.95018 (/home/runner/work/_actions/upptime/uptime-monitor/v1.30.0/webpack:/@upptime/uptime-monitor/node_modules/node-libcurl/dist/Curl.js:17:1)
```

**To Reproduce**
1. Go to Actions
2. Click run on any action
3. Action fails unless it's 'Update Template'

**Expected behavior**
Actions should run without the above error

**Screenshots**

<img width="1119" alt="Screenshot 2024-07-05 at 7 46 52 AM" src="https://github.com/upptime/upptime/assets/68383195/64b3c8bf-d0b9-474f-814e-da705e20fca6">

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Orion
 - Version: 0.99.127.3-beta

**Upptimerc.yml**
https://github.com/Whipcode-API/upptime/blob/master/.upptimerc.yml

PS. I have the uptime ci disabled temporarily since this issue started happening

**Comment by AnandChowdhary** [comment] 2024-07-05 10:59
Closing as duplicate of https://github.com/upptime/upptime/issues/800. I'm going to try and figure this out asap!

**Closed by AnandChowdhary** 2024-07-05 10:59 UTC
Labels: bug
