### ISSUE TITLE
https://demo.upptime.js.org/ not reachable

### ISSUE THREAD

**Issue by sphinx02** [upptime/upptime#455] opened 2021-10-05 10:05 UTC
Hi,
it seems as there is something broken. With the latest commit in gh-pages all static files have been deleted.

Does anyone know whats the reason?

**Comment by AnandChowdhary** [comment] 2021-10-05 10:16
Closing as duplicate of https://github.com/upptime/upptime/issues/453

**Closed by AnandChowdhary** 2021-10-05 10:16 UTC
Labels: bug
