### ISSUE TITLE
Upptime seemed still using Actions token despite GH_PAT is already supplied

### ISSUE THREAD

**Issue by Hans5958** [upptime/upptime#118] opened 2020-12-12 16:14 UTC
**Describe the bug**

It seems that in some way, there is a piece of code that uses the token that is supplied by GitHub Actions, located on the `GITHUB_TOKEN` environment variable. I think so because after generating new Upptime repositories and setting their respective  `GH_PAT` environment variable with my tokens on my other account, just because I want to avoid my contribution activity to be spammed with the updates. 

It worked, mostly. Most of the commits are directed to my other account, but there is a single commit that is present on the contribution activity of my profile every day.

I'm not sure if this is intended or what, but I ever tried to change the tokens myself when it is 1.x, after I realized that my contribution activity is spammed with response time commits, and it works perfectly, no Upptime commits on this account.

**To Reproduce**

1. Generate a repository using the template repository.
2. Set the `GH_PAT` enviroment variable with the token from another account/collaborator, not the repository owner.
3. Wait for commits to be pushed.
4. Check the contribution activity on the other account's GitHub profile and click one of the latest day/box. Most of the commits are attributed to the other account. (intended)
5. Check the contribution activity on the owner's GitHub profile and click one of the latest day/box. A single commit is present from the generated Upptime repository.

**Expected behavior**

There shouldn't be any commits from the generated Upptime repositories.

**Screenshots**
![image](https://user-images.githubusercontent.com/11584103/101988950-9758ad00-3ccf-11eb-97c1-d4b923e25335.png)

**Desktop (please complete the following information):**

 - OS: Windows 10
 - Browser: Mozilla Firefox
 - Version 83.0

**Additional context**

Due to the nature that there is only one commit that are pushed every day, that means that it is caused by one of the daily workflows. I tried to investigate it, and it seems that it boils down into these three commits.

- :card_file_box: Update status summary [skip ci] [upptime]
- :memo: Update summary in README [skip ci] [upptime]
- :bento: Update graphs [skip ci] 

By correlating it with the workflows, it seems that it is caused by either the "Summary CI" or the "Graphs CI".

I have no way to confirm if this is right, so please investigate this further.

**Comment by AnandChowdhary** [comment] 2020-12-19 06:30
Upptime doesn't use the `GITHUB_TOKEN` anywhere in the codebase if `GH_PAT` is specified. Furthermore, if it were to use `GITHUB_TOKEN`, the contributor would not be @Hans5958 but "GitHub Actions", so this is likely something else.

My best guess is that pushing to GitHub Pages counts as a contribution, and it's done by you for some reason, not your robot: https://github.com/Hans5958/Scratch-Upptime/tree/gh-pages. We use [maxheld83/ghpages](https://github.com/maxheld83/ghpages) for deploying to the `gh-pages` branch [using the `GH_PAT`](https://github.com/Hans5958/Scratch-Upptime/blob/master/.github/workflows/site.yml#L32), but GitHub still likes to show @Hans5958 as the committer.

I've checked and this is consistent with other repos, where I'm the committer instead of @upptime-bot, even though the PAT is of the bot account. Another interesting bit is that because the workflow is scheduled, GitHub determines the "scheduler" themselves, see https://github.com/Hans5958/Scratch-Upptime/actions/runs/431718118. Here, the workflow says "Triggered via schedule 5 hours ago \[by] @Hans5958", which is most likely why pushing to Github Pages makes them the author.

At this point, I don't think there's anything we can do but ask Github to fix/change this. Ideally, GitHub would not assign a user to scheduled workflows. For now, perhaps you can make a commit to https://github.com/Hans5958/Scratch-Upptime/blob/master/.github/workflows/site.yml from the bot account so GitHub recognizes you as the "legit most recent contributor" and assigns the scheduled workflows to the bot. I'd also recommend using the GitHub UI for this because perhaps it doesn't count API requests, otherwise the bot would already be the most recent contributor.

**Comment by jerrykan** [comment] 2021-01-13 04:46
I hit this issue as well, so I decided to dig into it a bit to see what is going on.

It seems like the problem is due to how the [maxheld83/ghpages](https://github.com/maxheld83/ghpages) action sets the git committer. From [entrypoint.sh#L21](https://github.com/maxheld83/ghpages/blob/master/entrypoint.sh#L21):
```
git config user.name "${GITHUB_ACTOR}" && \
git config user.email "${GITHUB_ACTOR}@users.noreply.github.com" && \
```
From the [Github Actions Doco](https://docs.github.com/en/free-pro-team@latest/actions/reference/environment-variables#default-environment-variables):
>  `GITHUB_ACTOR` - The name of the person or app that initiated the workflow. For example, `octocat`.

I didn't go digging any further as to how the Github Actions determines the person or app.

---

To fix the problem I made a personal clone/tag of the action and [changed the two lines](https://github.com/jerrykan/ghpages/commit/283154ebe6045cf1f089df11cc73320a78267c6f) to:
```
git config user.name "${GH_COMMITTER:-$GITHUB_ACTOR}" && \
git config user.email "${GH_COMMITTER:-$GITHUB_ACTOR}@users.noreply.github.com" && \
```
Then updated the `.github/workflows/site.yml`:
```
      - uses: jerrykan/ghpages@v0.3.0.1
        name: GitHub Pages Deploy
        env:
          BUILD_DIR: "site/status-page/__sapper__/export/"
          GH_COMMITTER: "github-username"
          GH_PAT: ${{ secrets.GH_PAT }}
```
If no `GH_COMMITTER` is provided the committer will default to `GITHUB_ACTOR`.

---

If I get a chance I might see if this change can be merged upstream so users can control who the committer is without need to for the action.

**Comment by AnandChowdhary** [comment] 2021-01-13 05:54
This is great, @jerrykan! Do you think you can make a PR there referencing this issue? If it's not accepted, I'd be happy to start using your fork instead.

**Comment by jerrykan** [comment] 2021-01-13 12:57
@AnandChowdhary Done! I've slightly reworked it so that setting the committer values is a bit more flexible, but the concept is essentially the same. We'll see if it gets merged upstream.

**Comment by AnandChowdhary** [comment] 2021-02-28 09:35
This is now fixed, we've switched to using [peaceiris/actions-gh-pages](https://github.com/peaceiris/actions-gh-pages) instead, which supports custom committers. Upptime will now respect the committer in your configuration and use it for GitHub Pages:

**Closed by AnandChowdhary** 2021-02-28 09:35 UTC
Labels: bug, uptime-monitor

**Comment by sumanthratna** [comment] 2021-03-03 14:34
> This is now fixed, we've switched to using [peaceiris/actions-gh-pages](https://github.com/peaceiris/actions-gh-pages) instead, which supports custom committers. Upptime will now respect the committer in your configuration and use it for GitHub Pages:

Hi @AnandChowdhary, it looks like Upptime is now pushing to GH pages without polluting my contribution graph, which is good. I'm wondering if `GH_PAT` is still needed. If I want, am I allowed to un-set the `GH_PAT` secret? For my case I would prefer `GITHUB_TOKEN` to be used everywhere without needing to set `GH_PAT`

**Comment by AnandChowdhary** [comment] 2021-03-05 13:10
Hey @sumanthratna, that's a perfectly valid request, and I would love that @upptime doesn't need a personal access token. 

I've tested this thoroughly, and it seems like almost all functionality (with the exception of updating Upptime itself) can be achieved using the default repository token. Updating workflows, however, requires the `workflow` scope which is unavailable to the default token. So, "Update Template CI" is the only workflow that wouldn't work with `GITHUB_TOKEN`, but I think that's an important one.

Would love to hear your thoughts on whether we should make updates optional and use the default token, or use the default token for everything other than updates, but still ask users you provide their personal access token for the updates. Updates happen infrequently, but are very important as they offer new functionality and security updates.

**Comment by sumanthratna** [comment] 2021-03-05 14:46
Thanks for looking into this @AnandChowdhary! I think auto-updates are an important but very useful feature so Upptime should use the default token whenever possible and use the user-provided PAT for updates. Can you explain why the `workflow` is needed? I'm a bit confused by how updates work (https://github.com/upptime/updates/blob/master/src/index.ts doesn't seem to update any code). I would personally prefer receiving PRs for updates (instead of direct commits) or commits from @upptime-bot or @github-actions[bot] if it means I don't need to provide a PAT

BTW I don't mean to hijack this thread so if it's easier for you we can move to a new issue or discussion
