### ISSUE TITLE
All sites are marked down. Please check!

### ISSUE THREAD

**Issue by belhyun** [upptime/upptime#49] opened 2020-11-03 00:53 UTC
All sites are marked down. Please check!

**Comment by gwanryo** [comment] 2020-11-03 02:43
I can't sure, but maybe there's problem with [recent uptime-monitor changes](https://github.com/upptime/uptime-monitor/blob/99d4198614e4ec94ce4ce2773c986cc25b44abfd/src/update.ts#L98)

**Comment by AndrewLaneX** [comment] 2020-11-03 02:44
Possibly related to the custom commits (https://github.com/upptime/uptime-monitor/commit/07b1dfed18b98a503eb4cd159b27d5e7d33b0360).

**Comment by gwanryo** [comment] 2020-11-03 02:51
> Possibly related to the custom commits ([upptime/uptime-monitor@07b1dfe](https://github.com/upptime/uptime-monitor/commit/07b1dfed18b98a503eb4cd159b27d5e7d33b0360)).

Maybe broken commit message (for example, upptime@5a143bfb0efd507ef59e765d7b088f06199c969e) affected all other functions

**Comment by AndrewLaneX** [comment] 2020-11-03 03:48
Seems so :thinking:
https://github.com/upptime/uptime-monitor/blob/master/src/summary.ts

**Comment by gwanryo** [comment] 2020-11-03 05:49
https://github.com/upptime/uptime-monitor/blob/master/src/update.ts#L100
`.replace(new RegExp("$EMOJI", "g"), status === "up" ? "🟩" : "🟥")`

https://github.com/gwanryo/uptime-monitor/blob/master/src/update.ts#L100
`.replace("$EMOJI", status === "up" ? "🟩" : "🟥")`

Removing 'new RegExp' makes code work properly.

**Comment by AnandChowdhary** [comment] 2020-11-03 05:57
Thanks for reporting this! I added these changes last night and woke up to this broken regex. 😢 Luckily, only the summary is broken, the sites aren't actually marked as down (for example as GitHub issues). The RegExp should be fixed now, I think the problem was the "$", I'm testing it now.

**Comment by gwanryo** [comment] 2020-11-03 06:12
Thanks! 😄

**Comment by AnandChowdhary** [comment] 2020-11-03 06:17
Yep, this is fine now! 😄 https://github.com/upptime/upptime

However, since the README.md and response time commits are updated once every day, you would've had to manually run "Setup CI" to see it all updated. For now, I've added updating the response time and README.md to "Uptime CI" which runs every 5 minutes, so after the next hour, I'll remove that. By then, all README.md files and response time commits should be updated back.

**Comment by AnandChowdhary** [comment] 2020-11-03 06:19
Thank you again @belhyun, @gwanryo, and @AndrewLaneX for reporting this so quickly, and I'm sorry this broke last night. I'll make sure I add a comprehensive set of test suites in the coming weeks to make sure something like this doesn't happen again. I'm closing this issue now, but please let me know if something still doesn't work for any of you.

**Closed by AnandChowdhary** 2020-11-03 06:19 UTC

**Comment by ShulertApp** [comment] 2020-11-03 14:34
We are still having red lines at https://status.shulert.com. We merged your PR and ran all workflows manually. What are we missing?

**Comment by AnandChowdhary** [comment] 2020-11-03 14:47
Your `summary.json` file was last updated 13 hours ago: https://github.com/Shulert/status/blob/master/history/summary.json and says "down".  This is weird because "Summary CI" should update this file as well.

**Comment by ShulertApp** [comment] 2020-11-03 14:51
> Your `summary.json` file was last updated 13 hours ago: https://github.com/Shulert/status/blob/master/history/summary.json and says "down". This is weird because "Summary CI" should update this file as well.

I have manually changed them to "up". Will the workflow automatically change them if the sites were to go down now?

**Comment by AnandChowdhary** [comment] 2020-11-03 14:55
Yes, absolutely. However, all other files were also updated 13 hours ago, and not when you more recently ran workflows. "Response Time CI" should have updated them, but it didn't because of the privacy settings of your repository (see https://github.com/Shulert/status/runs/1347532641?check_suite_focus=true). You should update these settings and run "Response Time CI" manually and everything should auto-update.

![Screen Shot 2020-11-03 at 20 24 37](https://user-images.githubusercontent.com/2841780/98000531-9bf98e00-1e12-11eb-8692-8063fb399e9f.png)

Most likely, you have checked "Block command line pushes that expose my email": https://stackoverflow.com/a/44099011/1656944. What I'll do is that I'll also internally switch to using the `noreply` GitHub email to make commits.

**Comment by ShulertApp** [comment] 2020-11-03 14:58
> Yes, absolutely. However, all other files were also updated 13 hours ago, and not when you more recently ran workflows. "Response Time CI" should have updated them, but it didn't because of the privacy settings of your repository (see https://github.com/Shulert/status/runs/1347532641?check_suite_focus=true). You should update these settings and run "Response Time CI" manually and everything should auto-update.

I was just about to send a message asking if this was the cause. 😄 I was looking through the logs and noticed this. Thanks so much!

**Comment by AnandChowdhary** [comment] 2020-11-03 15:00
I've also updated the bot's email address to commit using `73812536+upptime-bot@users.noreply.github.com` instead, so the commits will continue to work for repositories that have this enhanced privacy setting checked. 😄
