### ISSUE TITLE
Customize the webpage

### ISSUE THREAD

**Issue by sayantan300** [upptime/upptime#86] opened 2020-11-24 05:38 UTC
Hello koj team & @AnandChowdhary , I have a instance of upptime running, my site is at [here](https://status.rovelstars.ga) and it looks like it shows at below that `This page is open source, powered by Upptime` and I don't love this last part. Also the icon of the website stays the same old upptime logo instead of the one I wrote in config. So therefore I want to change the website source code, so can I know where do I need to change it?

**Comment by AnandChowdhary** [comment] 2020-11-24 06:45
You can remove the "powered by" part, it's a FAQ: https://upptime.js.org/docs/faq#how-do-i-remove-the-powered-by-upptime-in-the-footer-of-my-website

You can also customize the icon on top: https://upptime.js.org/docs/configuration#branding, but you're right, maybe the favicon doesn't change right now, I'll make sure I add that too.

We're going to add some customization features for colors and themes, so I'm closing this as a duplicate of #70.

**Closed by AnandChowdhary** 2020-11-24 06:45 UTC
